# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e236e8f0-d51a-4465-944e-74664099bdd0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e236e8f0-d51a-4465-944e-74664099bdd0".device = "/dev/disk/by-uuid/e236e8f0-d51a-4465-944e-74664099bdd0";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DD6A-4539";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-4bdf8f69-d4c1-4ab7-b3ff-d1c214ee354a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
