#!/usr/bin/python

import os
import enum
import sys

class ExitCodes(enum.IntEnum):
    SUCCESS = 0
    FAILURE = 1
    # 1 is automatically used if Python throws an exception
    NO_PASS_CANDIDATES = 2
    COULD_NOT_MATCH_USERNAME = 3
    COULD_NOT_MATCH_PASSWORD = 4

def main():
    url = os.environ['QUTE_URL']

    print(f"Retrieving ticket num from: {url}")

    if "https://phabricator.codeyellow.nl/" not in url:
        import sys
        print("URL is not a phabricator link from CodeYellow!")
        sys.exit(1)

    import subprocess

    ticket = url.split('/')[-1][1:]
    print(f"ticket is {ticket}")
    subprocess.run("wl-copy", text=True, input=ticket)

    return ExitCodes.SUCCESS


if __name__ == '__main__':
    sys.exit(main())

